/*
Slurm Rest API

API to access and control Slurm.

API version: 0.0.37
Contact: sales@schedmd.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package slurmclient

import (
	"encoding/json"
)

// checks if the V0037DiagRpcm type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V0037DiagRpcm{}

// V0037DiagRpcm struct for V0037DiagRpcm
type V0037DiagRpcm struct {
	// message type
	MessageType *string `json:"message_type,omitempty"`
	// message type id
	TypeId *int32 `json:"type_id,omitempty"`
	// rpc count
	Count *int32 `json:"count,omitempty"`
	// average time
	AveTime *int32 `json:"ave_time,omitempty"`
	// total time
	TotalTime *int32 `json:"total_time,omitempty"`
}

// NewV0037DiagRpcm instantiates a new V0037DiagRpcm object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV0037DiagRpcm() *V0037DiagRpcm {
	this := V0037DiagRpcm{}
	return &this
}

// NewV0037DiagRpcmWithDefaults instantiates a new V0037DiagRpcm object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV0037DiagRpcmWithDefaults() *V0037DiagRpcm {
	this := V0037DiagRpcm{}
	return &this
}

// GetMessageType returns the MessageType field value if set, zero value otherwise.
func (o *V0037DiagRpcm) GetMessageType() string {
	if o == nil || IsNil(o.MessageType) {
		var ret string
		return ret
	}
	return *o.MessageType
}

// GetMessageTypeOk returns a tuple with the MessageType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0037DiagRpcm) GetMessageTypeOk() (*string, bool) {
	if o == nil || IsNil(o.MessageType) {
		return nil, false
	}
	return o.MessageType, true
}

// HasMessageType returns a boolean if a field has been set.
func (o *V0037DiagRpcm) HasMessageType() bool {
	if o != nil && !IsNil(o.MessageType) {
		return true
	}

	return false
}

// SetMessageType gets a reference to the given string and assigns it to the MessageType field.
func (o *V0037DiagRpcm) SetMessageType(v string) {
	o.MessageType = &v
}

// GetTypeId returns the TypeId field value if set, zero value otherwise.
func (o *V0037DiagRpcm) GetTypeId() int32 {
	if o == nil || IsNil(o.TypeId) {
		var ret int32
		return ret
	}
	return *o.TypeId
}

// GetTypeIdOk returns a tuple with the TypeId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0037DiagRpcm) GetTypeIdOk() (*int32, bool) {
	if o == nil || IsNil(o.TypeId) {
		return nil, false
	}
	return o.TypeId, true
}

// HasTypeId returns a boolean if a field has been set.
func (o *V0037DiagRpcm) HasTypeId() bool {
	if o != nil && !IsNil(o.TypeId) {
		return true
	}

	return false
}

// SetTypeId gets a reference to the given int32 and assigns it to the TypeId field.
func (o *V0037DiagRpcm) SetTypeId(v int32) {
	o.TypeId = &v
}

// GetCount returns the Count field value if set, zero value otherwise.
func (o *V0037DiagRpcm) GetCount() int32 {
	if o == nil || IsNil(o.Count) {
		var ret int32
		return ret
	}
	return *o.Count
}

// GetCountOk returns a tuple with the Count field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0037DiagRpcm) GetCountOk() (*int32, bool) {
	if o == nil || IsNil(o.Count) {
		return nil, false
	}
	return o.Count, true
}

// HasCount returns a boolean if a field has been set.
func (o *V0037DiagRpcm) HasCount() bool {
	if o != nil && !IsNil(o.Count) {
		return true
	}

	return false
}

// SetCount gets a reference to the given int32 and assigns it to the Count field.
func (o *V0037DiagRpcm) SetCount(v int32) {
	o.Count = &v
}

// GetAveTime returns the AveTime field value if set, zero value otherwise.
func (o *V0037DiagRpcm) GetAveTime() int32 {
	if o == nil || IsNil(o.AveTime) {
		var ret int32
		return ret
	}
	return *o.AveTime
}

// GetAveTimeOk returns a tuple with the AveTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0037DiagRpcm) GetAveTimeOk() (*int32, bool) {
	if o == nil || IsNil(o.AveTime) {
		return nil, false
	}
	return o.AveTime, true
}

// HasAveTime returns a boolean if a field has been set.
func (o *V0037DiagRpcm) HasAveTime() bool {
	if o != nil && !IsNil(o.AveTime) {
		return true
	}

	return false
}

// SetAveTime gets a reference to the given int32 and assigns it to the AveTime field.
func (o *V0037DiagRpcm) SetAveTime(v int32) {
	o.AveTime = &v
}

// GetTotalTime returns the TotalTime field value if set, zero value otherwise.
func (o *V0037DiagRpcm) GetTotalTime() int32 {
	if o == nil || IsNil(o.TotalTime) {
		var ret int32
		return ret
	}
	return *o.TotalTime
}

// GetTotalTimeOk returns a tuple with the TotalTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V0037DiagRpcm) GetTotalTimeOk() (*int32, bool) {
	if o == nil || IsNil(o.TotalTime) {
		return nil, false
	}
	return o.TotalTime, true
}

// HasTotalTime returns a boolean if a field has been set.
func (o *V0037DiagRpcm) HasTotalTime() bool {
	if o != nil && !IsNil(o.TotalTime) {
		return true
	}

	return false
}

// SetTotalTime gets a reference to the given int32 and assigns it to the TotalTime field.
func (o *V0037DiagRpcm) SetTotalTime(v int32) {
	o.TotalTime = &v
}

func (o V0037DiagRpcm) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V0037DiagRpcm) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.MessageType) {
		toSerialize["message_type"] = o.MessageType
	}
	if !IsNil(o.TypeId) {
		toSerialize["type_id"] = o.TypeId
	}
	if !IsNil(o.Count) {
		toSerialize["count"] = o.Count
	}
	if !IsNil(o.AveTime) {
		toSerialize["ave_time"] = o.AveTime
	}
	if !IsNil(o.TotalTime) {
		toSerialize["total_time"] = o.TotalTime
	}
	return toSerialize, nil
}

type NullableV0037DiagRpcm struct {
	value *V0037DiagRpcm
	isSet bool
}

func (v NullableV0037DiagRpcm) Get() *V0037DiagRpcm {
	return v.value
}

func (v *NullableV0037DiagRpcm) Set(val *V0037DiagRpcm) {
	v.value = val
	v.isSet = true
}

func (v NullableV0037DiagRpcm) IsSet() bool {
	return v.isSet
}

func (v *NullableV0037DiagRpcm) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV0037DiagRpcm(val *V0037DiagRpcm) *NullableV0037DiagRpcm {
	return &NullableV0037DiagRpcm{value: val, isSet: true}
}

func (v NullableV0037DiagRpcm) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV0037DiagRpcm) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


