/*
Slurm REST API

API to access and control Slurm

API version: Slurm-24.05.8&openapi/slurmctld&openapi/slurmdbd
Contact: sales@schedmd.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the SlurmV0041PostNodeRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SlurmV0041PostNodeRequest{}

// SlurmV0041PostNodeRequest struct for SlurmV0041PostNodeRequest
type SlurmV0041PostNodeRequest struct {
	// Arbitrary comment
	Comment *string `json:"comment,omitempty"`
	// Default method for binding tasks to allocated CPUs
	CpuBind *int32 `json:"cpu_bind,omitempty"`
	// Arbitrary string used for node filtering if extra constraints are enabled
	Extra *string `json:"extra,omitempty"`
	// Available features
	Features []string `json:"features,omitempty"`
	// Currently active features
	FeaturesAct []string `json:"features_act,omitempty"`
	// Generic resources
	Gres *string `json:"gres,omitempty"`
	// NodeAddr, used to establish a communication path
	Address []string `json:"address,omitempty"`
	// NodeHostname
	Hostname []string `json:"hostname,omitempty"`
	// NodeName
	Name []string `json:"name,omitempty"`
	// New state to assign to the node
	State []string `json:"state,omitempty"`
	// Reason for node being DOWN or DRAINING
	Reason *string `json:"reason,omitempty"`
	// User ID to associate with the reason (needed if user root is sending message)
	ReasonUid *string `json:"reason_uid,omitempty"`
	ResumeAfter *SlurmV0041PostNodeRequestResumeAfter `json:"resume_after,omitempty"`
	Weight *SlurmV0041PostNodeRequestWeight `json:"weight,omitempty"`
}

// NewSlurmV0041PostNodeRequest instantiates a new SlurmV0041PostNodeRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSlurmV0041PostNodeRequest() *SlurmV0041PostNodeRequest {
	this := SlurmV0041PostNodeRequest{}
	return &this
}

// NewSlurmV0041PostNodeRequestWithDefaults instantiates a new SlurmV0041PostNodeRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSlurmV0041PostNodeRequestWithDefaults() *SlurmV0041PostNodeRequest {
	this := SlurmV0041PostNodeRequest{}
	return &this
}

// GetComment returns the Comment field value if set, zero value otherwise.
func (o *SlurmV0041PostNodeRequest) GetComment() string {
	if o == nil || IsNil(o.Comment) {
		var ret string
		return ret
	}
	return *o.Comment
}

// GetCommentOk returns a tuple with the Comment field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SlurmV0041PostNodeRequest) GetCommentOk() (*string, bool) {
	if o == nil || IsNil(o.Comment) {
		return nil, false
	}
	return o.Comment, true
}

// HasComment returns a boolean if a field has been set.
func (o *SlurmV0041PostNodeRequest) HasComment() bool {
	if o != nil && !IsNil(o.Comment) {
		return true
	}

	return false
}

// SetComment gets a reference to the given string and assigns it to the Comment field.
func (o *SlurmV0041PostNodeRequest) SetComment(v string) {
	o.Comment = &v
}

// GetCpuBind returns the CpuBind field value if set, zero value otherwise.
func (o *SlurmV0041PostNodeRequest) GetCpuBind() int32 {
	if o == nil || IsNil(o.CpuBind) {
		var ret int32
		return ret
	}
	return *o.CpuBind
}

// GetCpuBindOk returns a tuple with the CpuBind field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SlurmV0041PostNodeRequest) GetCpuBindOk() (*int32, bool) {
	if o == nil || IsNil(o.CpuBind) {
		return nil, false
	}
	return o.CpuBind, true
}

// HasCpuBind returns a boolean if a field has been set.
func (o *SlurmV0041PostNodeRequest) HasCpuBind() bool {
	if o != nil && !IsNil(o.CpuBind) {
		return true
	}

	return false
}

// SetCpuBind gets a reference to the given int32 and assigns it to the CpuBind field.
func (o *SlurmV0041PostNodeRequest) SetCpuBind(v int32) {
	o.CpuBind = &v
}

// GetExtra returns the Extra field value if set, zero value otherwise.
func (o *SlurmV0041PostNodeRequest) GetExtra() string {
	if o == nil || IsNil(o.Extra) {
		var ret string
		return ret
	}
	return *o.Extra
}

// GetExtraOk returns a tuple with the Extra field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SlurmV0041PostNodeRequest) GetExtraOk() (*string, bool) {
	if o == nil || IsNil(o.Extra) {
		return nil, false
	}
	return o.Extra, true
}

// HasExtra returns a boolean if a field has been set.
func (o *SlurmV0041PostNodeRequest) HasExtra() bool {
	if o != nil && !IsNil(o.Extra) {
		return true
	}

	return false
}

// SetExtra gets a reference to the given string and assigns it to the Extra field.
func (o *SlurmV0041PostNodeRequest) SetExtra(v string) {
	o.Extra = &v
}

// GetFeatures returns the Features field value if set, zero value otherwise.
func (o *SlurmV0041PostNodeRequest) GetFeatures() []string {
	if o == nil || IsNil(o.Features) {
		var ret []string
		return ret
	}
	return o.Features
}

// GetFeaturesOk returns a tuple with the Features field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SlurmV0041PostNodeRequest) GetFeaturesOk() ([]string, bool) {
	if o == nil || IsNil(o.Features) {
		return nil, false
	}
	return o.Features, true
}

// HasFeatures returns a boolean if a field has been set.
func (o *SlurmV0041PostNodeRequest) HasFeatures() bool {
	if o != nil && !IsNil(o.Features) {
		return true
	}

	return false
}

// SetFeatures gets a reference to the given []string and assigns it to the Features field.
func (o *SlurmV0041PostNodeRequest) SetFeatures(v []string) {
	o.Features = v
}

// GetFeaturesAct returns the FeaturesAct field value if set, zero value otherwise.
func (o *SlurmV0041PostNodeRequest) GetFeaturesAct() []string {
	if o == nil || IsNil(o.FeaturesAct) {
		var ret []string
		return ret
	}
	return o.FeaturesAct
}

// GetFeaturesActOk returns a tuple with the FeaturesAct field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SlurmV0041PostNodeRequest) GetFeaturesActOk() ([]string, bool) {
	if o == nil || IsNil(o.FeaturesAct) {
		return nil, false
	}
	return o.FeaturesAct, true
}

// HasFeaturesAct returns a boolean if a field has been set.
func (o *SlurmV0041PostNodeRequest) HasFeaturesAct() bool {
	if o != nil && !IsNil(o.FeaturesAct) {
		return true
	}

	return false
}

// SetFeaturesAct gets a reference to the given []string and assigns it to the FeaturesAct field.
func (o *SlurmV0041PostNodeRequest) SetFeaturesAct(v []string) {
	o.FeaturesAct = v
}

// GetGres returns the Gres field value if set, zero value otherwise.
func (o *SlurmV0041PostNodeRequest) GetGres() string {
	if o == nil || IsNil(o.Gres) {
		var ret string
		return ret
	}
	return *o.Gres
}

// GetGresOk returns a tuple with the Gres field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SlurmV0041PostNodeRequest) GetGresOk() (*string, bool) {
	if o == nil || IsNil(o.Gres) {
		return nil, false
	}
	return o.Gres, true
}

// HasGres returns a boolean if a field has been set.
func (o *SlurmV0041PostNodeRequest) HasGres() bool {
	if o != nil && !IsNil(o.Gres) {
		return true
	}

	return false
}

// SetGres gets a reference to the given string and assigns it to the Gres field.
func (o *SlurmV0041PostNodeRequest) SetGres(v string) {
	o.Gres = &v
}

// GetAddress returns the Address field value if set, zero value otherwise.
func (o *SlurmV0041PostNodeRequest) GetAddress() []string {
	if o == nil || IsNil(o.Address) {
		var ret []string
		return ret
	}
	return o.Address
}

// GetAddressOk returns a tuple with the Address field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SlurmV0041PostNodeRequest) GetAddressOk() ([]string, bool) {
	if o == nil || IsNil(o.Address) {
		return nil, false
	}
	return o.Address, true
}

// HasAddress returns a boolean if a field has been set.
func (o *SlurmV0041PostNodeRequest) HasAddress() bool {
	if o != nil && !IsNil(o.Address) {
		return true
	}

	return false
}

// SetAddress gets a reference to the given []string and assigns it to the Address field.
func (o *SlurmV0041PostNodeRequest) SetAddress(v []string) {
	o.Address = v
}

// GetHostname returns the Hostname field value if set, zero value otherwise.
func (o *SlurmV0041PostNodeRequest) GetHostname() []string {
	if o == nil || IsNil(o.Hostname) {
		var ret []string
		return ret
	}
	return o.Hostname
}

// GetHostnameOk returns a tuple with the Hostname field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SlurmV0041PostNodeRequest) GetHostnameOk() ([]string, bool) {
	if o == nil || IsNil(o.Hostname) {
		return nil, false
	}
	return o.Hostname, true
}

// HasHostname returns a boolean if a field has been set.
func (o *SlurmV0041PostNodeRequest) HasHostname() bool {
	if o != nil && !IsNil(o.Hostname) {
		return true
	}

	return false
}

// SetHostname gets a reference to the given []string and assigns it to the Hostname field.
func (o *SlurmV0041PostNodeRequest) SetHostname(v []string) {
	o.Hostname = v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *SlurmV0041PostNodeRequest) GetName() []string {
	if o == nil || IsNil(o.Name) {
		var ret []string
		return ret
	}
	return o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SlurmV0041PostNodeRequest) GetNameOk() ([]string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *SlurmV0041PostNodeRequest) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given []string and assigns it to the Name field.
func (o *SlurmV0041PostNodeRequest) SetName(v []string) {
	o.Name = v
}

// GetState returns the State field value if set, zero value otherwise.
func (o *SlurmV0041PostNodeRequest) GetState() []string {
	if o == nil || IsNil(o.State) {
		var ret []string
		return ret
	}
	return o.State
}

// GetStateOk returns a tuple with the State field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SlurmV0041PostNodeRequest) GetStateOk() ([]string, bool) {
	if o == nil || IsNil(o.State) {
		return nil, false
	}
	return o.State, true
}

// HasState returns a boolean if a field has been set.
func (o *SlurmV0041PostNodeRequest) HasState() bool {
	if o != nil && !IsNil(o.State) {
		return true
	}

	return false
}

// SetState gets a reference to the given []string and assigns it to the State field.
func (o *SlurmV0041PostNodeRequest) SetState(v []string) {
	o.State = v
}

// GetReason returns the Reason field value if set, zero value otherwise.
func (o *SlurmV0041PostNodeRequest) GetReason() string {
	if o == nil || IsNil(o.Reason) {
		var ret string
		return ret
	}
	return *o.Reason
}

// GetReasonOk returns a tuple with the Reason field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SlurmV0041PostNodeRequest) GetReasonOk() (*string, bool) {
	if o == nil || IsNil(o.Reason) {
		return nil, false
	}
	return o.Reason, true
}

// HasReason returns a boolean if a field has been set.
func (o *SlurmV0041PostNodeRequest) HasReason() bool {
	if o != nil && !IsNil(o.Reason) {
		return true
	}

	return false
}

// SetReason gets a reference to the given string and assigns it to the Reason field.
func (o *SlurmV0041PostNodeRequest) SetReason(v string) {
	o.Reason = &v
}

// GetReasonUid returns the ReasonUid field value if set, zero value otherwise.
func (o *SlurmV0041PostNodeRequest) GetReasonUid() string {
	if o == nil || IsNil(o.ReasonUid) {
		var ret string
		return ret
	}
	return *o.ReasonUid
}

// GetReasonUidOk returns a tuple with the ReasonUid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SlurmV0041PostNodeRequest) GetReasonUidOk() (*string, bool) {
	if o == nil || IsNil(o.ReasonUid) {
		return nil, false
	}
	return o.ReasonUid, true
}

// HasReasonUid returns a boolean if a field has been set.
func (o *SlurmV0041PostNodeRequest) HasReasonUid() bool {
	if o != nil && !IsNil(o.ReasonUid) {
		return true
	}

	return false
}

// SetReasonUid gets a reference to the given string and assigns it to the ReasonUid field.
func (o *SlurmV0041PostNodeRequest) SetReasonUid(v string) {
	o.ReasonUid = &v
}

// GetResumeAfter returns the ResumeAfter field value if set, zero value otherwise.
func (o *SlurmV0041PostNodeRequest) GetResumeAfter() SlurmV0041PostNodeRequestResumeAfter {
	if o == nil || IsNil(o.ResumeAfter) {
		var ret SlurmV0041PostNodeRequestResumeAfter
		return ret
	}
	return *o.ResumeAfter
}

// GetResumeAfterOk returns a tuple with the ResumeAfter field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SlurmV0041PostNodeRequest) GetResumeAfterOk() (*SlurmV0041PostNodeRequestResumeAfter, bool) {
	if o == nil || IsNil(o.ResumeAfter) {
		return nil, false
	}
	return o.ResumeAfter, true
}

// HasResumeAfter returns a boolean if a field has been set.
func (o *SlurmV0041PostNodeRequest) HasResumeAfter() bool {
	if o != nil && !IsNil(o.ResumeAfter) {
		return true
	}

	return false
}

// SetResumeAfter gets a reference to the given SlurmV0041PostNodeRequestResumeAfter and assigns it to the ResumeAfter field.
func (o *SlurmV0041PostNodeRequest) SetResumeAfter(v SlurmV0041PostNodeRequestResumeAfter) {
	o.ResumeAfter = &v
}

// GetWeight returns the Weight field value if set, zero value otherwise.
func (o *SlurmV0041PostNodeRequest) GetWeight() SlurmV0041PostNodeRequestWeight {
	if o == nil || IsNil(o.Weight) {
		var ret SlurmV0041PostNodeRequestWeight
		return ret
	}
	return *o.Weight
}

// GetWeightOk returns a tuple with the Weight field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SlurmV0041PostNodeRequest) GetWeightOk() (*SlurmV0041PostNodeRequestWeight, bool) {
	if o == nil || IsNil(o.Weight) {
		return nil, false
	}
	return o.Weight, true
}

// HasWeight returns a boolean if a field has been set.
func (o *SlurmV0041PostNodeRequest) HasWeight() bool {
	if o != nil && !IsNil(o.Weight) {
		return true
	}

	return false
}

// SetWeight gets a reference to the given SlurmV0041PostNodeRequestWeight and assigns it to the Weight field.
func (o *SlurmV0041PostNodeRequest) SetWeight(v SlurmV0041PostNodeRequestWeight) {
	o.Weight = &v
}

func (o SlurmV0041PostNodeRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SlurmV0041PostNodeRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Comment) {
		toSerialize["comment"] = o.Comment
	}
	if !IsNil(o.CpuBind) {
		toSerialize["cpu_bind"] = o.CpuBind
	}
	if !IsNil(o.Extra) {
		toSerialize["extra"] = o.Extra
	}
	if !IsNil(o.Features) {
		toSerialize["features"] = o.Features
	}
	if !IsNil(o.FeaturesAct) {
		toSerialize["features_act"] = o.FeaturesAct
	}
	if !IsNil(o.Gres) {
		toSerialize["gres"] = o.Gres
	}
	if !IsNil(o.Address) {
		toSerialize["address"] = o.Address
	}
	if !IsNil(o.Hostname) {
		toSerialize["hostname"] = o.Hostname
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.State) {
		toSerialize["state"] = o.State
	}
	if !IsNil(o.Reason) {
		toSerialize["reason"] = o.Reason
	}
	if !IsNil(o.ReasonUid) {
		toSerialize["reason_uid"] = o.ReasonUid
	}
	if !IsNil(o.ResumeAfter) {
		toSerialize["resume_after"] = o.ResumeAfter
	}
	if !IsNil(o.Weight) {
		toSerialize["weight"] = o.Weight
	}
	return toSerialize, nil
}

type NullableSlurmV0041PostNodeRequest struct {
	value *SlurmV0041PostNodeRequest
	isSet bool
}

func (v NullableSlurmV0041PostNodeRequest) Get() *SlurmV0041PostNodeRequest {
	return v.value
}

func (v *NullableSlurmV0041PostNodeRequest) Set(val *SlurmV0041PostNodeRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableSlurmV0041PostNodeRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableSlurmV0041PostNodeRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSlurmV0041PostNodeRequest(val *SlurmV0041PostNodeRequest) *NullableSlurmV0041PostNodeRequest {
	return &NullableSlurmV0041PostNodeRequest{value: val, isSet: true}
}

func (v NullableSlurmV0041PostNodeRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSlurmV0041PostNodeRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


