/*
Slurm REST API

API to access and control Slurm

API version: Slurm-24.05.8&openapi/slurmctld&openapi/slurmdbd
Contact: sales@schedmd.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the SlurmV0041PostNodeRequestWeight type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SlurmV0041PostNodeRequestWeight{}

// SlurmV0041PostNodeRequestWeight Weight of the node for scheduling purposes
type SlurmV0041PostNodeRequestWeight struct {
	// True if number has been set; False if number is unset
	Set *bool `json:"set,omitempty"`
	// True if number has been set to infinite; \"set\" and \"number\" will be ignored
	Infinite *bool `json:"infinite,omitempty"`
	// If \"set\" is True the number will be set with value; otherwise ignore number contents
	Number *int32 `json:"number,omitempty"`
}

// NewSlurmV0041PostNodeRequestWeight instantiates a new SlurmV0041PostNodeRequestWeight object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSlurmV0041PostNodeRequestWeight() *SlurmV0041PostNodeRequestWeight {
	this := SlurmV0041PostNodeRequestWeight{}
	return &this
}

// NewSlurmV0041PostNodeRequestWeightWithDefaults instantiates a new SlurmV0041PostNodeRequestWeight object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSlurmV0041PostNodeRequestWeightWithDefaults() *SlurmV0041PostNodeRequestWeight {
	this := SlurmV0041PostNodeRequestWeight{}
	return &this
}

// GetSet returns the Set field value if set, zero value otherwise.
func (o *SlurmV0041PostNodeRequestWeight) GetSet() bool {
	if o == nil || IsNil(o.Set) {
		var ret bool
		return ret
	}
	return *o.Set
}

// GetSetOk returns a tuple with the Set field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SlurmV0041PostNodeRequestWeight) GetSetOk() (*bool, bool) {
	if o == nil || IsNil(o.Set) {
		return nil, false
	}
	return o.Set, true
}

// HasSet returns a boolean if a field has been set.
func (o *SlurmV0041PostNodeRequestWeight) HasSet() bool {
	if o != nil && !IsNil(o.Set) {
		return true
	}

	return false
}

// SetSet gets a reference to the given bool and assigns it to the Set field.
func (o *SlurmV0041PostNodeRequestWeight) SetSet(v bool) {
	o.Set = &v
}

// GetInfinite returns the Infinite field value if set, zero value otherwise.
func (o *SlurmV0041PostNodeRequestWeight) GetInfinite() bool {
	if o == nil || IsNil(o.Infinite) {
		var ret bool
		return ret
	}
	return *o.Infinite
}

// GetInfiniteOk returns a tuple with the Infinite field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SlurmV0041PostNodeRequestWeight) GetInfiniteOk() (*bool, bool) {
	if o == nil || IsNil(o.Infinite) {
		return nil, false
	}
	return o.Infinite, true
}

// HasInfinite returns a boolean if a field has been set.
func (o *SlurmV0041PostNodeRequestWeight) HasInfinite() bool {
	if o != nil && !IsNil(o.Infinite) {
		return true
	}

	return false
}

// SetInfinite gets a reference to the given bool and assigns it to the Infinite field.
func (o *SlurmV0041PostNodeRequestWeight) SetInfinite(v bool) {
	o.Infinite = &v
}

// GetNumber returns the Number field value if set, zero value otherwise.
func (o *SlurmV0041PostNodeRequestWeight) GetNumber() int32 {
	if o == nil || IsNil(o.Number) {
		var ret int32
		return ret
	}
	return *o.Number
}

// GetNumberOk returns a tuple with the Number field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SlurmV0041PostNodeRequestWeight) GetNumberOk() (*int32, bool) {
	if o == nil || IsNil(o.Number) {
		return nil, false
	}
	return o.Number, true
}

// HasNumber returns a boolean if a field has been set.
func (o *SlurmV0041PostNodeRequestWeight) HasNumber() bool {
	if o != nil && !IsNil(o.Number) {
		return true
	}

	return false
}

// SetNumber gets a reference to the given int32 and assigns it to the Number field.
func (o *SlurmV0041PostNodeRequestWeight) SetNumber(v int32) {
	o.Number = &v
}

func (o SlurmV0041PostNodeRequestWeight) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SlurmV0041PostNodeRequestWeight) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Set) {
		toSerialize["set"] = o.Set
	}
	if !IsNil(o.Infinite) {
		toSerialize["infinite"] = o.Infinite
	}
	if !IsNil(o.Number) {
		toSerialize["number"] = o.Number
	}
	return toSerialize, nil
}

type NullableSlurmV0041PostNodeRequestWeight struct {
	value *SlurmV0041PostNodeRequestWeight
	isSet bool
}

func (v NullableSlurmV0041PostNodeRequestWeight) Get() *SlurmV0041PostNodeRequestWeight {
	return v.value
}

func (v *NullableSlurmV0041PostNodeRequestWeight) Set(val *SlurmV0041PostNodeRequestWeight) {
	v.value = val
	v.isSet = true
}

func (v NullableSlurmV0041PostNodeRequestWeight) IsSet() bool {
	return v.isSet
}

func (v *NullableSlurmV0041PostNodeRequestWeight) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSlurmV0041PostNodeRequestWeight(val *SlurmV0041PostNodeRequestWeight) *NullableSlurmV0041PostNodeRequestWeight {
	return &NullableSlurmV0041PostNodeRequestWeight{value: val, isSet: true}
}

func (v NullableSlurmV0041PostNodeRequestWeight) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSlurmV0041PostNodeRequestWeight) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


